//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIG_Banners
    {
        public int ID { get; set; }
        public string BANNER_IMG { get; set; }
        public string BANNER_DESCRIPTION { get; set; }
        public string BANNER_HEADER { get; set; }
        public string BANNER_SUB_HEADER { get; set; }
        public string IS_ACTIVE { get; set; }
    }
}
