//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIG_Policy
    {
        public int ID { get; set; }
        public string POLICY { get; set; }
        public string VISION { get; set; }
        public string OBLIGATION { get; set; }
        public string ACTIVITY { get; set; }
    }
}
