//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIG_About
    {
        public int ID { get; set; }
        public string WHO_WE_ARE { get; set; }
        public string WHY_US { get; set; }
        public string IS_EXECUTIVE_INFO { get; set; }
        public string AUTHOR { get; set; }
        public string EXECUTIVE_INFOMATION { get; set; }
    }
}
